allowBuilds:
  '@serialport/bindings-cpp': true
  '@stoprocent/bluetooth-hci-socket': true
  '@stoprocent/noble': true
  esbuild: true
  sharp: true
  usb: true
  usocket: true

ignoredBuiltDependencies:
  - '@serialport/bindings-cpp'
  - '@stoprocent/bluetooth-hci-socket'
  - '@stoprocent/noble'

onlyBuiltDependencies:
  - '@abandonware/bluetooth-hci-socket'
  - '@abandonware/noble'
  - esbuild
  - sharp
  - usb
